// GENERATED by tool/form_glyphs/build_form_glyphs.py -- do not edit by hand.

import 'package:flutter/widgets.dart';

/// Option glyphs for the trade-form question cards, traced from the
/// form-flow mockup (workholding, measuring instruments, turning
/// operations).
///
/// They live in the bundled `BbFormGlyphs` icon font (24-unit grid,
/// 1.75-unit round stroke, laid out like MaterialIcons) and are used like
/// Material icons: `Icon(FormGlyphs.collet, size: 20)`. Change a glyph by
/// editing its strokes in `tool/form_glyphs/build_form_glyphs.py` and
/// re-running it; the script regenerates both the font and this file.
abstract final class FormGlyphs {
  static const String _family = 'BbFormGlyphs';

  /// `three_jaw` -- Teen jaw chuck.
  static const IconData teenJawChuck = IconData(0xE000, fontFamily: _family);

  /// `four_jaw` -- Chaar jaw chuck.
  static const IconData chaarJawChuck = IconData(0xE001, fontFamily: _family);

  /// `collet` -- Collet.
  static const IconData collet = IconData(0xE002, fontFamily: _family);

  /// `soft_jaw` -- Soft jaw.
  static const IconData softJaw = IconData(0xE003, fontFamily: _family);

  /// `tailstock` -- Tailstock ya centre.
  static const IconData tailstockCentre = IconData(0xE004, fontFamily: _family);

  /// `steady_rest` -- Steady rest.
  static const IconData steadyRest = IconData(0xE005, fontFamily: _family);

  /// `vernier` -- Vernier caliper.
  static const IconData vernierCaliper = IconData(0xE006, fontFamily: _family);

  /// `micrometer` -- Micrometer.
  static const IconData micrometer = IconData(0xE007, fontFamily: _family);

  /// `bore_gauge` -- Bore dial gauge.
  static const IconData boreDialGauge = IconData(0xE008, fontFamily: _family);

  /// `height_gauge` -- Height gauge.
  static const IconData heightGauge = IconData(0xE009, fontFamily: _family);

  /// `plug_gauge` -- Plug ya ring gauge.
  static const IconData plugRingGauge = IconData(0xE00A, fontFamily: _family);

  /// `dial_indicator` -- Dial indicator.
  static const IconData dialIndicator = IconData(0xE00B, fontFamily: _family);

  /// `facing_od` -- Facing aur OD turning.
  static const IconData facingOdTurning = IconData(0xE00C, fontFamily: _family);

  /// `boring` -- Boring, ID turning.
  static const IconData boringIdTurning = IconData(0xE00D, fontFamily: _family);

  /// `threading` -- Threading.
  static const IconData threading = IconData(0xE00E, fontFamily: _family);

  /// `grooving` -- Grooving aur parting.
  static const IconData groovingParting = IconData(0xE00F, fontFamily: _family);

  /// `drilling` -- Drilling aur tapping.
  static const IconData drillingTapping = IconData(0xE010, fontFamily: _family);

  /// `knurling` -- Knurling aur taper.
  static const IconData knurlingTaper = IconData(0xE011, fontFamily: _family);
}
