// #1432 — measures the worker app's OWN `titleCaseName` on the Dart VM, so the TypeScript port
// (`../title-case.ts`) is held to what the app does on every Unicode scalar value rather than to
// a reading of its source. Writes `title-case.dart-vm.json` beside this file.
//
// Regenerate from the repository root (Git Bash on Windows: prefix MSYS_NO_PATHCONV=1):
//
//   docker run --rm \
//     -v "$PWD/apps/worker-app/lib/core/util:/app:ro" \
//     -v "$PWD/packages/validators/src/__fixtures__:/fixtures" \
//     dart:3.9 dart run /fixtures/title-case.dart-vm.probe.dart
//   pnpm exec prettier --write packages/validators/src/__fixtures__/title-case.dart-vm.json
//
// `dart:3.9` is the Dart inside Flutter 3.35.7, the toolchain the app is built on (ci.yml).
//
// The function under test is IMPORTED from the app, never copied, and every property the
// TypeScript suite relies on is MEASURED through it: which code points break a word (from
// "a<c>b"), what a word-initial code point becomes (from "<c>"), and that nothing after a word's
// first code point ever changes (from "x<c>"). An input that fits none of those shapes is listed
// under `anomalies`, which the suite requires to be empty.
import 'dart:convert';
import 'dart:io';

import 'file:///app/title_case.dart';

List<int> cps(String s) => s.runes.toList();

void main() {
  final whitespace = <int>[];
  final upper = <List<int>>[];
  final anomalies = <int>[];
  for (var cp = 0; cp <= 0x10FFFF; cp++) {
    if (cp >= 0xD800 && cp <= 0xDFFF) continue; // not scalar values; a String cannot hold one alone
    final c = String.fromCharCode(cp);
    final around = titleCaseName('a${c}b');
    if (around == 'A${c}B') {
      whitespace.add(cp);
    } else if (around != 'A${c}b') {
      anomalies.add(cp);
    }
    if (titleCaseName('x$c') != 'X$c') anomalies.add(cp);
    final alone = titleCaseName(c);
    if (alone != c) upper.add([cp, ...cps(alone)]);
  }

  // Whole strings, for the walk itself: the app's own test cases, the edges the TypeScript suite
  // names, and 200 seeded random strings over a pool that over-weights every class above.
  final fixed = <String>[
    'rvm cad pvt lt', 'faridabad', 'Asha Kumari', 'RVM CAD', 'ITI Faridabad', 'NIFT',
    'mCA institute', '', 'govt  iti', '3d cad institute',
    'recursive global infotech pvt ltd', 'CNC Operator', '  spaced  out  ',
    'cnc\tturner\nfitter\r\nwelder', 'a\u0085b', 'shri ram auto-parts (india)', 'l&t',
    'm/s sharma engineering', "shri ram's auto", 'फरीदाबाद', 'आईटीआई faridabad',
    '\u{10428}\u{1042F} x', 'éclair', 'éclair', 'ßauer', 'ﬁtter shop',
    'ᾀ ᾳ ῃ ῳ ǅ ǆ ǈ', 'ɥ ა ꭰ \u{1E922}',
  ];
  final pool = <int>[
    for (var i = 0; i < 26; i++) 0x61 + i,
    for (var i = 0; i < 26; i++) 0x41 + i,
    0x20, 0x20, 0x20, 0x09, 0x0A, 0x85, 0xA0, 0x1680, 0x2007, 0x202F, 0x3000, 0xFEFF, 0x200B,
    0x180E, 0x2D, 0x28, 0x26, 0x27, 0x2F, 0x2E, 0x30, 0x39, 0xDF, 0xFF, 0xB5, 0x149, 0x1C5,
    0x1C6, 0x1F80, 0x1FB3, 0x1F50, 0xFB01, 0x0915, 0x093F, 0x10428, 0x1E922, 0x0301, 0xE9,
    0x131, 0x130, 0x3C2, 0x587, 0x1E96, 0x265, 0x10D0, 0xAB70,
  ];
  var seed = 1432;
  int next() => seed = (seed * 1103515245 + 12345) & 0x7FFFFFFF;
  final random = <String>[
    for (var i = 0; i < 200; i++)
      String.fromCharCodes([for (var j = next() % 12; j > 0; j--) pool[next() % pool.length]]),
  ];
  final strings = <List<List<int>>>[
    for (final s in [...fixed, ...random]) [cps(s), cps(titleCaseName(s))],
  ];

  final out = {
    '_comment': [
      'GENERATED by title-case.dart-vm.probe.dart — measured, not written. Do not edit by hand.',
      'The worker app\'s titleCaseName on the Dart VM: `whitespace` breaks a word, `upper` maps a',
      'word-initial code point (every scalar value not listed is left as is), `strings` are whole',
      'inputs and outputs as code points. Read by title-case.test.ts (#1432).',
    ],
    'dart': Platform.version.split(' ').first,
    'whitespace': whitespace,
    'upper': upper,
    'anomalies': anomalies,
    'strings': strings,
  };
  File('/fixtures/title-case.dart-vm.json').writeAsStringSync('${jsonEncode(out)}\n');
  stdout.writeln('whitespace=${whitespace.length} upper=${upper.length} '
      'anomalies=${anomalies.length} strings=${strings.length}');
}
