/**
 * ANN scale simulation — what the retrieval QUERY does as the corpus grows toward
 * production size.
 *
 *   pnpm db:scale:taxonomy --plan                 # what would be built. Writes nothing.
 *   pnpm db:scale:taxonomy --run --sizes 1000,2000,5000,9121
 *   pnpm db:scale:taxonomy --teardown             # drop the sandbox schema
 *
 * ===========================================================================
 * WHAT THIS MEASURES, AND — MORE IMPORTANTLY — WHAT IT DOES NOT
 * ===========================================================================
 * The Phase 5 baseline reported Recall@1 99.1% over 197 real embeddings, and then had to
 * carry a caveat that swallowed the number: `EXPLAIN ANALYZE` showed a Seq Scan, so the
 * HNSW index was never consulted and the measurement was EXACT nearest-neighbour. Exact NN
 * is an upper bound. Nobody could say what happens when the index actually engages, because
 * 197 rows is far too few to make the planner choose it.
 *
 * This harness answers that, and only that. It measures INFRASTRUCTURE:
 *
 *   - is the HNSW index used at all, at each corpus size (read from the plan, never assumed)
 *   - planning time and execution time
 *   - how many rows survive the domain filter, versus the k that was asked for
 *   - how ef_search and iterative_scan move those numbers
 *   - how often a scoped query comes back EMPTY
 *   - ANN recall against exact NN — an index property, computed from ground truth this
 *     harness derives itself
 *
 * IT DOES NOT MEASURE RETRIEVAL QUALITY, and it cannot. The padding vectors are synthetic;
 * they carry no meaning, so "did the right skill come back" is not a question that has an
 * answer here. Every quality field in the experiment record it writes is null, and
 * `assertNoSemanticClaim` exists so a later change cannot quietly start filling them in.
 *
 * ===========================================================================
 * WHY THE PADDING IS PERTURBED REAL VECTORS, NOT RANDOM ONES
 * ===========================================================================
 * The obvious way to reach 9k rows is to generate uniform random unit vectors. It is also
 * useless, and quietly so. In 768 dimensions two random vectors are almost exactly
 * orthogonal, so random padding sits at cosine ~0 to every query: HNSW walks straight past
 * it to the real cluster and reports ~100% recall at every ef_search. The experiment would
 * conclude that the index is free, which is the opposite of what a dense corpus does.
 *
 * So padding is generated by perturbing a REAL corpus vector with Gaussian noise and
 * renormalizing. The noise scale controls how crowded the neighbourhood gets, and crowding
 * is precisely what makes an approximate search approximate. This produces a corpus with
 * realistic local density and no semantic content whatsoever — the right shape for an index
 * experiment and the wrong shape for a quality one, which is the trade this harness wants.
 *
 * The generator is SEEDED. An experiment nobody can re-run is an anecdote.
 *
 * ===========================================================================
 * IT CANNOT TOUCH THE REAL CORPUS
 * ===========================================================================
 * Everything lives in a dedicated `taxonomy_scale_sim` schema that the harness creates and
 * drops. There is no migration, so the tables cannot reach any other environment, and the
 * runner never issues a write against `public.skill_alias` — `--teardown` drops the sandbox
 * schema by name and nothing else. The Phase 5 embeddings are the input to this experiment;
 * destroying them to run it would be a poor trade.
 */
import { config } from "dotenv";
import { sql as dsql } from "drizzle-orm";

import { createDbClient } from "./client";
import {
  UNKNOWN_ANN,
  isExperimentId,
  pushExperimentToLangfuse,
  writeExperimentRecord,
  type AnnConfig,
  type ExperimentId,
  type ExperimentRecord,
} from "./taxonomy-experiments";

config({ path: "../../.env" });

const SCRIPT = "scale:taxonomy";
export const SIM_SCHEMA = "taxonomy_scale_sim";
export const EMBEDDING_DIMENSION = 768;
/** Production target: the shipped alias vocabulary this taxonomy will eventually cover. */
export const PRODUCTION_ALIAS_TARGET = 9121;
export const DEFAULT_SIZES = [1000, 2000, 5000, PRODUCTION_ALIAS_TARGET];
/** Deterministic by default — a scale experiment must be re-runnable to be evidence. */
export const DEFAULT_SEED = 20260817;
/**
 * How similar a synthetic neighbour is to the real vector it was grown from.
 *
 * EXPRESSED AS A TARGET COSINE, NOT A NOISE SIGMA, and that is not cosmetic. Sigma is a
 * per-component quantity, so its effect depends on the dimensionality: at 768 dimensions a
 * unit vector's components are ~1/sqrt(768) ≈ 0.036, and a "small-sounding" sigma of 0.35
 * adds noise with norm 0.35*sqrt(768) ≈ 9.7 — ten times the signal, landing the result at
 * cosine 0.10, i.e. essentially ORTHOGONAL. That was the first value tried here and a test
 * caught it. It would have produced padding that competes with nothing, HNSW recall of
 * ~100% at every ef_search, and a confident conclusion that the index is free.
 *
 * 0.85 puts the padding in the band the real corpus shows between genuinely confusable
 * siblings — the Phase 5 diagnosis measured rank-1 hits at ~0.79-0.88 with competitors
 * 0.19-0.46 below. Crowding is what makes an approximate search approximate, so this is the
 * single most consequential knob in the harness. It is recorded in the experiment.
 */
export const DEFAULT_NEIGHBOUR_COSINE = 0.85;
/** A query is a PARAPHRASE of one alias, not a different alias — much closer than padding. */
export const DEFAULT_QUERY_COSINE = 0.95;

/**
 * The per-component sigma that lands `parent + noise` at `targetCosine` from `parent`.
 *
 * For a unit parent and isotropic noise of norm n, cos = 1/sqrt(1 + n^2); inverting gives
 * n = sqrt(1/c^2 - 1), and n = sigma*sqrt(dim) for independent per-component Gaussians.
 * Deriving it means the knob stays meaningful if the embedding width ever changes.
 */
export function sigmaForCosine(targetCosine: number, dim: number = EMBEDDING_DIMENSION): number {
  if (!(targetCosine > 0 && targetCosine < 1)) {
    throw new Error(`[scale] targetCosine must be in (0, 1), got ${targetCosine}`);
  }
  return Math.sqrt(1 / (targetCosine * targetCosine) - 1) / Math.sqrt(dim);
}

// ===========================================================================
// Deterministic vector synthesis
// ===========================================================================

/** mulberry32 — small, fast, and identical across platforms, which `Math.random` is not. */
export function makeRng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Box-Muller. Two uniforms in, one standard normal out. */
export function gaussian(rng: () => number): number {
  // u must be non-zero: log(0) is -Infinity and would poison the whole vector.
  let u = 0;
  while (u === 0) u = rng();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * rng());
}

/**
 * A synthetic neighbour of `parent`: add Gaussian noise, then L2-normalize.
 *
 * Normalizing matters beyond tidiness — the real corpus is normalized by the ai-service, and
 * a padding set at a different magnitude would be trivially separable by cosine distance,
 * which is exactly the shortcut that would make the ANN look better than it is.
 */
export function perturb(parent: readonly number[], sigma: number, rng: () => number): number[] {
  const out = new Array<number>(parent.length);
  let norm = 0;
  for (let i = 0; i < parent.length; i += 1) {
    const v = (parent[i] as number) + gaussian(rng) * sigma;
    out[i] = v;
    norm += v * v;
  }
  norm = Math.sqrt(norm);
  if (norm === 0) throw new Error("[scale] perturbation produced a zero vector");
  for (let i = 0; i < out.length; i += 1) out[i] = (out[i] as number) / norm;
  return out;
}

export function cosine(a: readonly number[], b: readonly number[]): number {
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i += 1) {
    dot += (a[i] as number) * (b[i] as number);
    na += (a[i] as number) ** 2;
    nb += (b[i] as number) ** 2;
  }
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

// ===========================================================================
// The corpus shape being simulated
// ===========================================================================

/** The real taxonomy's shape, measured rather than guessed, so the padding matches it. */
export interface CorpusShape {
  aliasesPerSkill: number;
  skillsPerDomain: number;
  domainsPerSkill: number;
}

/**
 * How many synthetic skills and domains a target alias count implies.
 *
 * Derived from the MEASURED shape so the simulated corpus is the real one scaled up, not a
 * differently-shaped corpus of the same size. That distinction is load-bearing here: the
 * filtered-ANN behaviour this experiment is about depends on the SELECTIVITY of the domain
 * filter — how small a slice of the table one domain is — and selectivity is a function of
 * shape, not of row count. Padding with 9k aliases spread over 28 domains would make each
 * filter match a third of the table and show none of the pathology.
 */
export function planScale(targetAliases: number, realAliases: number, shape: CorpusShape): {
  syntheticAliases: number;
  syntheticSkills: number;
  syntheticDomains: number;
} {
  const syntheticAliases = Math.max(0, targetAliases - realAliases);
  const syntheticSkills = Math.max(1, Math.round(syntheticAliases / shape.aliasesPerSkill));
  // Each synthetic skill sits on `domainsPerSkill` edges, and each domain holds
  // `skillsPerDomain` of them.
  const syntheticDomains = Math.max(
    1,
    Math.round((syntheticSkills * shape.domainsPerSkill) / shape.skillsPerDomain),
  );
  return { syntheticAliases, syntheticSkills, syntheticDomains };
}

// ===========================================================================
// Plan inspection
// ===========================================================================

/** What the planner actually did. Read from EXPLAIN — never inferred from index existence. */
export interface PlanFacts {
  hnswUsed: boolean;
  seqScan: boolean;
  planningMs: number;
  executionMs: number;
  actualRows: number;
  nodeTypes: string[];
  indexNames: string[];
}

/**
 * Walk an `EXPLAIN (ANALYZE, FORMAT JSON)` tree.
 *
 * `hnswUsed` requires BOTH an index-scan node AND that the index it names is the HNSW one.
 * A plan can use `skill_alias_skill_id_idx` and still sort every candidate by distance,
 * which is exact NN with extra steps — counting that as "the ANN engaged" would report the
 * caveat as resolved while it is still in force.
 */
export function readPlan(explain: unknown, hnswIndexName: string): PlanFacts {
  const root = Array.isArray(explain) ? (explain[0] as Record<string, unknown>) : (explain as Record<string, unknown>);
  const plan = root?.["Plan"] as Record<string, unknown> | undefined;
  const nodeTypes: string[] = [];
  const indexNames: string[] = [];
  let hnswUsed = false;
  let seqScan = false;

  const walk = (node: Record<string, unknown> | undefined): void => {
    if (!node) return;
    const type = String(node["Node Type"] ?? "");
    nodeTypes.push(type);
    if (type === "Seq Scan") seqScan = true;
    const indexName = node["Index Name"];
    if (typeof indexName === "string") {
      if (!indexNames.includes(indexName)) indexNames.push(indexName);
      if (indexName === hnswIndexName) hnswUsed = true;
    }
    for (const child of (node["Plans"] as Record<string, unknown>[] | undefined) ?? []) walk(child);
  };
  walk(plan);

  return {
    hnswUsed,
    seqScan,
    planningMs: Number(root?.["Planning Time"] ?? 0),
    executionMs: Number(root?.["Execution Time"] ?? 0),
    actualRows: Number(plan?.["Actual Rows"] ?? 0),
    nodeTypes,
    indexNames,
  };
}

/** Overlap of two ranked id lists — the ANN's recall against exact NN at the same depth. */
export function recallVsExact(ann: readonly string[], exact: readonly string[]): number | null {
  if (exact.length === 0) return null; // nothing to recall; 1.0 here would be a free pass
  const want = new Set(exact);
  return Math.round((ann.filter((id) => want.has(id)).length / exact.length) * 10_000) / 10_000;
}

// ===========================================================================
// Result shapes
// ===========================================================================

/** One (size, configuration) measurement. */
export interface ScalePoint {
  corpus_rows: number;
  label: string;
  ef_search: number | null;
  iterative_scan: string | null;
  /** true = index scans disabled, i.e. the exact-NN ground truth run. */
  exact: boolean;
  scoped: boolean;
  queries: number;
  hnsw_used: boolean;
  seq_scan: boolean;
  planning_ms_p50: number;
  execution_ms_p50: number;
  execution_ms_p90: number;
  latency_ms_p50: number;
  latency_ms_p90: number;
  /** Mean rows the query returned. Below `k` on a scoped ANN query is THE finding. */
  returned_rows_mean: number;
  returned_rows_min: number;
  /** Share of queries that returned NOTHING. */
  empty_rate: number;
  /** Overlap with the exact run at the same size/scope. null on the exact run itself. */
  ann_recall_vs_exact: number | null;
  /** The plan's node types, and any index it named. Kept because "hnsw=no, seq=no" is a
   *  real and important outcome — the planner chose a THIRD path — and a boolean pair
   *  cannot say which one, which is exactly what a production recommendation turns on. */
  plan_nodes: string[];
  plan_indexes: string[];
}

export function percentile(xs: readonly number[], p: number): number {
  if (xs.length === 0) return NaN;
  const s = [...xs].sort((a, b) => a - b);
  const i = Math.min(s.length - 1, Math.max(0, Math.ceil((p / 100) * s.length) - 1));
  return Math.round((s[i] as number) * 1000) / 1000;
}

/**
 * Guard: this harness may never publish a semantic quality number.
 *
 * The padding has no meaning, so a Recall@1 computed over it would be a statement about
 * random vectors wearing the name of a retrieval metric. The record is checked before it is
 * written, because the realistic failure is not malice — it is a later change reusing the
 * shared ExperimentRecord and populating the quality fields because they were there.
 */
export function assertNoSemanticClaim(rec: ExperimentRecord): void {
  for (const [field, value] of [
    ["recall_at_1", rec.recall_at_1],
    ["recall_at_3", rec.recall_at_3],
    ["recall_at_5", rec.recall_at_5],
    ["mrr", rec.mrr],
  ] as const) {
    if (value !== null) {
      throw new Error(
        `[${SCRIPT}] refusing to record ${field}=${String(value)} from a scale simulation. The ` +
          `padding vectors are synthetic and carry no meaning, so a semantic retrieval metric ` +
          `over them would be a number about noise. Infrastructure findings belong in detail.`,
      );
    }
  }
}

// ===========================================================================
// CLI
// ===========================================================================

function arg(argv: readonly string[], flag: string): string | null {
  const eq = argv.find((a) => a.startsWith(`${flag}=`));
  if (eq !== undefined) {
    const v = eq.slice(flag.length + 1);
    if (v.length === 0) throw new Error(`[${SCRIPT}] ${flag}= was given with no value.`);
    return v;
  }
  const i = argv.indexOf(flag);
  if (i < 0) return null;
  const v = argv[i + 1];
  if (v === undefined || v.startsWith("--")) throw new Error(`[${SCRIPT}] ${flag} requires a value.`);
  return v;
}

function parseSizes(raw: string | null): number[] {
  if (raw === null) return DEFAULT_SIZES;
  const sizes = raw.split(",").map((s) => Number(s.trim()));
  if (sizes.some((n) => !Number.isInteger(n) || n < 1)) {
    throw new Error(`[${SCRIPT}] --sizes must be a comma-separated list of positive integers`);
  }
  return sizes.sort((a, b) => a - b);
}

async function main(): Promise<void> {
  const argv = process.argv;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error(`[${SCRIPT}] DATABASE_URL is not set`);
  const sizes = parseSizes(arg(argv, "--sizes"));
  const seed = Number(arg(argv, "--seed") ?? DEFAULT_SEED);
  const neighbourCosine = Number(arg(argv, "--neighbour-cosine") ?? DEFAULT_NEIGHBOUR_COSINE);
  const queryCosine = Number(arg(argv, "--query-cosine") ?? DEFAULT_QUERY_COSINE);
  const sigma = sigmaForCosine(neighbourCosine);
  const querySigma = sigmaForCosine(queryCosine);
  const k = Number(arg(argv, "--k") ?? 5);
  const overfetch = Number(arg(argv, "--overfetch") ?? 8);
  const queriesPerPoint = Number(arg(argv, "--queries") ?? 40);
  const experimentRaw = arg(argv, "--experiment");
  if (experimentRaw !== null && !isExperimentId(experimentRaw)) {
    throw new Error(`[${SCRIPT}] --experiment ${experimentRaw} is not a known experiment`);
  }
  const experiment = experimentRaw as ExperimentId | null;

  const { db, sql } = createDbClient(url, { max: 1 });
  const hnswIndex = "sim_alias_embedding_hnsw";

  try {
    if (argv.includes("--teardown")) {
      await db.execute(dsql.raw(`DROP SCHEMA IF EXISTS ${SIM_SCHEMA} CASCADE`));
      console.log(`[${SCRIPT}] dropped schema ${SIM_SCHEMA}`);
      return;
    }

    // ── read the REAL corpus: vectors and shape ────────────────────────────
    const real = (await db.execute(
      dsql`SELECT sa.id::text AS id, sa.skill_id, sa.text, sa.embedding::text AS embedding
           FROM skill_alias sa WHERE sa.embedding IS NOT NULL ORDER BY sa.id`,
    )) as unknown as { id: string; skill_id: string; text: string; embedding: string }[];
    const realEdges = (await db.execute(
      dsql`SELECT job_domain_id, skill_id FROM job_domain_skill WHERE status = 'active'`,
    )) as unknown as { job_domain_id: string; skill_id: string }[];

    if (real.length === 0) {
      console.error(
        `[${SCRIPT}] there are no embedded aliases to build a simulation from. The padding is ` +
          `derived by perturbing REAL vectors, so an empty corpus would leave nothing but noise ` +
          `and the ANN measurement would describe a distribution that does not exist. Run ` +
          `db:embed:skills first.`,
      );
      process.exitCode = 1;
      return;
    }

    const realVectors = real.map((r) => JSON.parse(r.embedding) as number[]);
    const realDomains = [...new Set(realEdges.map((e) => e.job_domain_id))].sort();
    const skillsPerDomain = realEdges.length / Math.max(1, realDomains.length);
    const distinctSkillsInEdges = new Set(realEdges.map((e) => e.skill_id)).size;
    const shape: CorpusShape = {
      aliasesPerSkill: real.length / Math.max(1, new Set(real.map((r) => r.skill_id)).size),
      skillsPerDomain,
      domainsPerSkill: realEdges.length / Math.max(1, distinctSkillsInEdges),
    };

    console.log(`[${SCRIPT}] real corpus`);
    console.log(`  embedded aliases         = ${real.length}`);
    console.log(`  active edges             = ${realEdges.length} over ${realDomains.length} domains`);
    console.log(`  aliases/skill            = ${shape.aliasesPerSkill.toFixed(3)}`);
    console.log(`  skills/domain            = ${shape.skillsPerDomain.toFixed(3)}`);
    console.log(`  domains/skill            = ${shape.domainsPerSkill.toFixed(3)}`);
    console.log(
    `  seed=${seed} neighbour_cos=${neighbourCosine} (sigma ${sigma.toFixed(5)}) ` +
      `query_cos=${queryCosine} (sigma ${querySigma.toFixed(5)}) k=${k} overfetch=${overfetch} ` +
      `queries/point=${queriesPerPoint}`,
  );

    if (argv.includes("--plan") || !argv.includes("--run")) {
      console.log(`[${SCRIPT}] PLAN — nothing created, nothing written`);
      for (const size of sizes) {
        const p = planScale(size, real.length, shape);
        console.log(
          `  target ${String(size).padStart(6)} aliases -> synthetic ${String(p.syntheticAliases).padStart(6)} ` +
            `over ${String(p.syntheticSkills).padStart(5)} skills / ${String(p.syntheticDomains).padStart(4)} domains`,
        );
      }
      console.log(`  sandbox schema           = ${SIM_SCHEMA} (created by --run, dropped by --teardown)`);
      console.log(`  writes to public.*       = NONE`);
      if (!argv.includes("--plan")) console.log(`[${SCRIPT}] no mode given. Use --plan | --run | --teardown`);
      return;
    }

    // ── build the sandbox ──────────────────────────────────────────────────
    await db.execute(dsql.raw(`DROP SCHEMA IF EXISTS ${SIM_SCHEMA} CASCADE`));
    await db.execute(dsql.raw(`CREATE SCHEMA ${SIM_SCHEMA}`));
    await db.execute(
      dsql.raw(`CREATE TABLE ${SIM_SCHEMA}.alias (
        id bigserial PRIMARY KEY,
        skill_id text NOT NULL,
        synthetic boolean NOT NULL,
        embedding vector(${EMBEDDING_DIMENSION})
      )`),
    );
    await db.execute(
      dsql.raw(`CREATE TABLE ${SIM_SCHEMA}.domain_skill (
        job_domain_id text NOT NULL,
        skill_id text NOT NULL,
        status text NOT NULL DEFAULT 'active'
      )`),
    );
    console.log(`[${SCRIPT}] created sandbox schema ${SIM_SCHEMA}`);

    const results: ScalePoint[] = [];
    let built = 0;

    for (const size of sizes) {
      // Grow INCREMENTALLY: each size builds on the last, so the 9121-row corpus contains
      // the 1000-row one. Rebuilding from scratch per size would give each point a
      // different random neighbourhood and make the sizes incomparable.
      if (built === 0) {
        const rows = real.map((r, i) => `('${r.skill_id.replace(/'/g, "''")}', false, '${JSON.stringify(realVectors[i])}')`);
        await insertBatched(sql, `${SIM_SCHEMA}.alias (skill_id, synthetic, embedding)`, rows);
        const edgeRows = realEdges.map(
          (e) => `('${e.job_domain_id.replace(/'/g, "''")}', '${e.skill_id.replace(/'/g, "''")}', 'active')`,
        );
        await insertBatched(sql, `${SIM_SCHEMA}.domain_skill (job_domain_id, skill_id, status)`, edgeRows);
        built = real.length;
      }

      const need = size - built;
      if (need > 0) {
        const rng = makeRng(seed + size);
        const aliasRows: string[] = [];
        const edgeRows: string[] = [];
        const startSkill = built; // keeps synthetic skill ids unique across growth steps
        let made = 0;
        let skillIdx = 0;
        while (made < need) {
          const skillId = `sim_skill_${startSkill}_${skillIdx}`;
          const perSkill = Math.max(1, Math.round(shape.aliasesPerSkill));
          for (let a = 0; a < perSkill && made < need; a += 1) {
            const parent = realVectors[Math.floor(rng() * realVectors.length)] as number[];
            aliasRows.push(`('${skillId}', true, '${JSON.stringify(perturb(parent, sigma, rng))}')`);
            made += 1;
          }
          // Wire the synthetic skill into SYNTHETIC domains only.
          //
          // Deliberately NOT into the real ones. Production grows by adding DOMAINS — 28
          // today, 4,071 eventually — while each domain keeps holding 6-11 skills. Letting
          // synthetic skills accumulate on the 28 real domains models the opposite corpus:
          // a smoke run did exactly that and inflated each real domain to ~19 skills, which
          // makes the domain filter LESS selective as the table grows. That is backwards,
          // and it hides the thing being measured — filtered HNSW degrades as the filter
          // gets MORE selective, because the index returns its ef_search candidates globally
          // and the join then discards nearly all of them. Keeping domains small at every
          // size is what reproduces production selectivity: ~8.5 rows out of 9,121.
          const edges = Math.max(1, Math.round(shape.domainsPerSkill));
          const perDomain = Math.max(1, Math.round(shape.skillsPerDomain));
          for (let e = 0; e < edges; e += 1) {
            // Spread each skill's edges across DIFFERENT synthetic domains, mirroring the
            // measured 1.817 domains/skill — a skill wired twice to one domain would be a
            // duplicate edge rather than multi-domain reach.
            const domain = `sim_domain_${startSkill}_${Math.floor(skillIdx / perDomain) + e * 7919}`;
            edgeRows.push(`('${domain}', '${skillId}', 'active')`);
          }
          skillIdx += 1;
        }
        await insertBatched(sql, `${SIM_SCHEMA}.alias (skill_id, synthetic, embedding)`, aliasRows);
        await insertBatched(sql, `${SIM_SCHEMA}.domain_skill (job_domain_id, skill_id, status)`, edgeRows);
        built = size;
      }

      // Index AFTER loading — building HNSW incrementally per row is far slower and is not
      // how a production backfill would do it either.
      await db.execute(dsql.raw(`DROP INDEX IF EXISTS ${SIM_SCHEMA}.${hnswIndex}`));
      await db.execute(
        dsql.raw(`CREATE INDEX ${hnswIndex} ON ${SIM_SCHEMA}.alias USING hnsw (embedding vector_cosine_ops)`),
      );
      await db.execute(dsql.raw(`CREATE INDEX IF NOT EXISTS sim_ds_domain ON ${SIM_SCHEMA}.domain_skill (job_domain_id)`));
      await db.execute(dsql.raw(`CREATE INDEX IF NOT EXISTS sim_alias_skill ON ${SIM_SCHEMA}.alias (skill_id)`));
      await db.execute(dsql.raw(`ANALYZE ${SIM_SCHEMA}.alias`));
      await db.execute(dsql.raw(`ANALYZE ${SIM_SCHEMA}.domain_skill`));

      const actual = Number(
        ((await db.execute(dsql.raw(`SELECT count(*)::int AS n FROM ${SIM_SCHEMA}.alias`))) as unknown as { n: number }[])[0]
          ?.n ?? 0,
      );
      console.log(`\n[${SCRIPT}] ===== corpus = ${actual} aliases =====`);

      // ── queries: a paraphrase of an alias that IS in the scope being queried ──
      //
      // Sampled from the LOADED corpus, not from the real set, so that at every size the
      // query has a genuine answer inside its own domain. A query perturbed from a real
      // vector but scoped to a synthetic domain would have no true neighbour in scope: the
      // ANN and the exact run would both return whatever that domain happens to hold, and
      // "recall vs exact" would measure agreement about noise. Drawing the query from its
      // own scope is what makes the comparison mean something.
      const sampleRows = (await sql.unsafe(
        `SELECT ds.job_domain_id AS domain, a.embedding::text AS embedding
         FROM ${SIM_SCHEMA}.alias a
         JOIN ${SIM_SCHEMA}.domain_skill ds ON ds.skill_id = a.skill_id
         WHERE a.embedding IS NOT NULL AND ds.status = 'active'
         ORDER BY md5(a.id::text || ds.job_domain_id)
         LIMIT ${queriesPerPoint}`,
      )) as unknown as { domain: string; embedding: string }[];
      const qrng = makeRng(seed ^ size);
      const queries = sampleRows.map((r) => ({
        // Much closer than the padding: a QUERY is a paraphrase of one alias, not a
        // different alias. Too much noise and every query is equidistant from everything,
        // which would make the ANN look bad for a reason unrelated to the index.
        vector: perturb(JSON.parse(r.embedding) as number[], querySigma, qrng),
        domain: r.domain,
      }));
      const scopeSizes = (await sql.unsafe(
        `SELECT avg(c)::float AS mean, min(c)::int AS lo, max(c)::int AS hi FROM (
           SELECT count(*) c FROM ${SIM_SCHEMA}.domain_skill WHERE status='active' GROUP BY job_domain_id
         ) t`,
      )) as unknown as { mean: number; lo: number; hi: number }[];
      const ss = scopeSizes[0];
      console.log(
        `  domains: skills/domain mean=${Number(ss?.mean ?? 0).toFixed(2)} ` +
          `min=${ss?.lo} max=${ss?.hi}  (filter selectivity ~${((Number(ss?.mean ?? 0) / actual) * 100).toFixed(3)}%)`,
      );

      for (const scoped of [true, false]) {
        const exact = await measure(sql, { label: "exact (seq)", exact: true, efSearch: null, iterativeScan: null }, queries, { k, overfetch, scoped, actual, hnswIndex });
        results.push(exact.point);
        printPoint(exact.point);

        const configs = [
          { label: "hnsw default", exact: false, efSearch: 40, iterativeScan: "off" },
          { label: "hnsw ef=20", exact: false, efSearch: 20, iterativeScan: "off" },
          { label: "hnsw ef=100", exact: false, efSearch: 100, iterativeScan: "off" },
          { label: "hnsw ef=200", exact: false, efSearch: 200, iterativeScan: "off" },
          { label: "hnsw ef=400", exact: false, efSearch: 400, iterativeScan: "off" },
          { label: "hnsw ef=40 iter=relaxed", exact: false, efSearch: 40, iterativeScan: "relaxed_order" },
          { label: "hnsw ef=40 iter=strict", exact: false, efSearch: 40, iterativeScan: "strict_order" },
        ];
        for (const cfg of configs) {
          const m = await measure(sql, cfg, queries, { k, overfetch, scoped, actual, hnswIndex });
          m.point.ann_recall_vs_exact = meanRecall(m.topk, exact.topk);
          results.push(m.point);
          printPoint(m.point);
        }
      }
    }

    // ── the records ────────────────────────────────────────────────────────
    //
    // ONE RUN, THREE EXPERIMENTS. A single sweep produces the points for all three ANN
    // experiments, and they are written SEPARATELY rather than as one blob: each answers a
    // different question ("does the index engage at all", "what does ef_search buy",
    // "does iterative_scan fix the filtered shortfall") and each has to be independently
    // re-readable and independently comparable across future runs. Splitting them here
    // costs nothing and keeps the registry's unit of comparison honest.
    if (argv.includes("--record")) {
      const largest = Math.max(...results.map((r) => r.corpus_rows));
      const stamp = new Date().toISOString();
      const families: { id: ExperimentId; keep: (p: ScalePoint) => boolean; ef: number | null; iter: string | null }[] = [
        {
          id: "EXP-ANN-DEFAULT",
          keep: (p) => p.exact || p.label === "hnsw default",
          ef: 40,
          iter: "off",
        },
        {
          id: "EXP-ANN-EF-SEARCH",
          keep: (p) => p.exact || (p.iterative_scan === "off" && p.label.startsWith("hnsw ef=")),
          ef: null,
          iter: "off",
        },
        {
          id: "EXP-ANN-ITERATIVE-SCAN",
          keep: (p) => p.exact || (p.iterative_scan !== null && p.iterative_scan !== "off"),
          ef: 40,
          iter: "relaxed_order|strict_order",
        },
      ];
      for (const fam of families) {
        if (experiment !== null && experiment !== fam.id) continue;
        const points = results.filter(fam.keep);
        const atLargest = points.filter((p) => p.corpus_rows === largest && !p.exact);
        const ann: AnnConfig = {
          ...UNKNOWN_ANN,
          corpus_rows: largest,
          // MEASURED from the plan at the largest size, never inferred from the index
          // existing. This single field is what the Phase 5 caveat turns on.
          hnsw_used: atLargest.length === 0 ? null : atLargest.some((p) => p.hnsw_used),
          ef_search: fam.ef,
          iterative_scan: fam.iter,
          k,
          alias_overfetch: overfetch,
        };
        const record: ExperimentRecord = {
          experiment: fam.id,
          run_id: `scale-seed${seed}-${fam.id}-${stamp}`,
          recorded_at: stamp,
          purpose: "ANN scale simulation — infrastructure behaviour only, no semantic claim.",
          evaluator_version: 0, // no evaluator ran: this is not a quality measurement
          fixture_id: null,
          fixture_version: null,
          corpus_batch: null,
          model: null,
          embedding_model: null,
          query_count: queriesPerPoint,
          failure_count: 0,
          latency_ms: null,
          recall_at_1: null,
          recall_at_3: null,
          recall_at_5: null,
          mrr: null,
          input_tokens: null,
          cost_inr_metered: null,
          cost_inr_estimated: null,
          ann,
          detail: {
            seed,
            neighbour_cosine: neighbourCosine,
            query_cosine: queryCosine,
            neighbour_sigma: sigma,
            query_sigma: querySigma,
            sizes,
            real_aliases: real.length,
            shape,
            points,
          },
          notes: [
            "SYNTHETIC CORPUS. Padding vectors are Gaussian perturbations of real embeddings, " +
              "renormalized to the same unit length, targeting cosine " +
              `${neighbourCosine} to their parent. They carry NO semantic content, so every ` +
              "quality field is null and assertNoSemanticClaim refuses a record that fills one " +
              "in. The only claims here are about the index and the query plan.",
            "ann_recall_vs_exact is an INDEX property: overlap between the HNSW result and the " +
              "SAME query run with index scans disabled. Ground truth is derived by this harness, " +
              "so no provider is involved and the whole experiment is credential-independent.",
            "Domain shape is held at production selectivity (~8.5 skills per domain) at EVERY " +
              "corpus size, because production grows by adding domains, not by enlarging them. " +
              "Letting domains grow instead would make the filter less selective as the table " +
              "grows and would hide the filtered-ANN shortfall this experiment exists to find.",
            `Zero provider calls. Zero writes outside the ${SIM_SCHEMA} schema.`,
          ],
        };
        assertNoSemanticClaim(record);
        const path = writeExperimentRecord(record);
        console.log(`[${SCRIPT}] recorded ${fam.id} (${points.length} points) -> ${path}`);
        if (argv.includes("--push-langfuse")) {
          console.log(`  langfuse mirror = ${JSON.stringify(await pushExperimentToLangfuse(record))}`);
        }
      }
    }

    if (!argv.includes("--keep")) {
      await db.execute(dsql.raw(`DROP SCHEMA IF EXISTS ${SIM_SCHEMA} CASCADE`));
      console.log(`[${SCRIPT}] sandbox dropped (pass --keep to inspect it)`);
    }
  } finally {
    await sql.end();
  }
}

/**
 * The bit of the postgres.js client this harness uses.
 *
 * Structural rather than `any`: everything below reaches for `sql.unsafe` because the
 * queries are assembled per configuration (GUCs, EXPLAIN prefixes, sandbox schema names)
 * and cannot be expressed as a Drizzle builder. Naming the one method keeps that
 * deliberate choice from widening into an untyped handle.
 */
type SqlClient = ReturnType<typeof createDbClient>["sql"];

/** Multi-row INSERT in chunks — one statement per 9k rows of 768 floats would not fly. */
async function insertBatched(sql: SqlClient, target: string, rows: string[], chunk = 200): Promise<void> {
  for (let i = 0; i < rows.length; i += chunk) {
    await sql.unsafe(`INSERT INTO ${target} VALUES ${rows.slice(i, i + chunk).join(",")}`);
  }
}

interface MeasureCfg {
  label: string;
  exact: boolean;
  efSearch: number | null;
  iterativeScan: string | null;
}

/**
 * Run one configuration over every query, with EXPLAIN on the first.
 *
 * The GUCs are set per query rather than once per configuration because the pooled
 * connection is shared and a leaked `SET` would silently apply to the next point. `SET
 * LOCAL` inside an explicit transaction is the version that cannot leak.
 */
async function measure(
  sql: SqlClient,
  cfg: MeasureCfg,
  queries: readonly { vector: number[]; domain: string }[],
  opts: { k: number; overfetch: number; scoped: boolean; actual: number; hnswIndex: string },
): Promise<{ point: ScalePoint; topk: string[][] }> {
  const limit = opts.k * opts.overfetch;
  const select = opts.scoped
    ? `SELECT sa.skill_id AS skill_id, 1 - (sa.embedding <=> $1::vector) AS score
       FROM ${SIM_SCHEMA}.alias sa
       JOIN ${SIM_SCHEMA}.domain_skill ds ON ds.skill_id = sa.skill_id
       WHERE ds.job_domain_id = $2 AND ds.status = 'active' AND sa.embedding IS NOT NULL
       ORDER BY sa.embedding <=> $1::vector
       LIMIT ${limit}`
    : `SELECT sa.skill_id AS skill_id, 1 - (sa.embedding <=> $1::vector) AS score
       FROM ${SIM_SCHEMA}.alias sa
       WHERE sa.embedding IS NOT NULL
       ORDER BY sa.embedding <=> $1::vector
       LIMIT ${limit}`;

  const planning: number[] = [];
  const execution: number[] = [];
  const latency: number[] = [];
  const returned: number[] = [];
  const topk: string[][] = [];
  let hnswUsed = false;
  let seqScan = false;
  let empties = 0;
  let planNodes: string[] = [];
  let planIndexes: string[] = [];

  for (const [i, q] of queries.entries()) {
    const params = opts.scoped ? [JSON.stringify(q.vector), q.domain] : [JSON.stringify(q.vector)];
    const guc: string[] = [];
    if (cfg.exact) {
      // Exact ground truth: force the planner off every index path so the ORDER BY is a
      // full sort over real distances.
      guc.push(`SET LOCAL enable_indexscan = off`, `SET LOCAL enable_bitmapscan = off`, `SET LOCAL enable_indexonlyscan = off`);
    } else {
      if (cfg.efSearch !== null) guc.push(`SET LOCAL hnsw.ef_search = ${cfg.efSearch}`);
      if (cfg.iterativeScan !== null) guc.push(`SET LOCAL hnsw.iterative_scan = '${cfg.iterativeScan}'`);
    }

    const t0 = Date.now();
    await sql.unsafe("BEGIN");
    try {
      for (const g of guc) await sql.unsafe(g);
      if (i === 0) {
        const ex = await sql.unsafe(`EXPLAIN (ANALYZE, FORMAT JSON) ${select}`, params);
        const raw = (ex[0] as Record<string, unknown>)["QUERY PLAN"];
        const facts = readPlan(typeof raw === "string" ? JSON.parse(raw) : raw, opts.hnswIndex);
        hnswUsed = facts.hnswUsed;
        seqScan = facts.seqScan;
        planNodes = facts.nodeTypes;
        planIndexes = facts.indexNames;
        planning.push(facts.planningMs);
        execution.push(facts.executionMs);
      }
      const rows = (await sql.unsafe(select, params)) as { skill_id: string }[];
      // Dedupe to SKILLS, as the production consumer does — the shortfall that matters is
      // in distinct skills offered, not alias rows scanned.
      const ids: string[] = [];
      for (const r of rows) if (!ids.includes(r.skill_id)) ids.push(r.skill_id);
      topk.push(ids.slice(0, opts.k));
      returned.push(ids.length);
      if (rows.length === 0) empties += 1;
    } finally {
      await sql.unsafe("COMMIT");
    }
    latency.push(Date.now() - t0);
  }

  return {
    topk,
    point: {
      corpus_rows: opts.actual,
      label: cfg.label,
      ef_search: cfg.efSearch,
      iterative_scan: cfg.iterativeScan,
      exact: cfg.exact,
      scoped: opts.scoped,
      queries: queries.length,
      hnsw_used: hnswUsed,
      seq_scan: seqScan,
      planning_ms_p50: percentile(planning, 50),
      execution_ms_p50: percentile(execution, 50),
      execution_ms_p90: percentile(execution, 90),
      latency_ms_p50: percentile(latency, 50),
      latency_ms_p90: percentile(latency, 90),
      returned_rows_mean: Math.round((returned.reduce((a, b) => a + b, 0) / Math.max(1, returned.length)) * 100) / 100,
      returned_rows_min: returned.length === 0 ? 0 : Math.min(...returned),
      empty_rate: Math.round((empties / Math.max(1, queries.length)) * 10_000) / 10_000,
      ann_recall_vs_exact: null,
      plan_nodes: planNodes,
      plan_indexes: planIndexes,
    },
  };
}

function meanRecall(ann: readonly string[][], exact: readonly string[][]): number | null {
  const vals: number[] = [];
  for (let i = 0; i < Math.min(ann.length, exact.length); i += 1) {
    const r = recallVsExact(ann[i] as string[], exact[i] as string[]);
    if (r !== null) vals.push(r);
  }
  if (vals.length === 0) return null;
  return Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 10_000) / 10_000;
}

function printPoint(p: ScalePoint): void {
  console.log(
    `  ${(p.scoped ? "scoped " : "global ") + p.label.padEnd(24)} ` +
      `hnsw=${p.hnsw_used ? "YES" : "no "} seq=${p.seq_scan ? "Y" : "n"} ` +
      `plan=${String(p.planning_ms_p50).padStart(7)}ms exec=${String(p.execution_ms_p50).padStart(8)}ms ` +
      `lat_p50=${String(p.latency_ms_p50).padStart(5)}ms lat_p90=${String(p.latency_ms_p90).padStart(5)}ms ` +
      `rows=${String(p.returned_rows_mean).padStart(5)} min=${String(p.returned_rows_min).padStart(3)} ` +
      `empty=${(p.empty_rate * 100).toFixed(1)}% ` +
      `recall_vs_exact=${p.ann_recall_vs_exact === null ? " n/a " : `${(p.ann_recall_vs_exact * 100).toFixed(1)}%`}`,
  );
  if (p.plan_indexes.length > 0 || p.plan_nodes.length > 0) {
    console.log(`      plan: ${p.plan_nodes.join(" > ")}   indexes: ${p.plan_indexes.join(", ") || "(none)"}`);
  }
}

if (process.argv[1] && /taxonomy-scale-sim\.ts$/.test(process.argv[1])) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
