import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ALL_ICON_NAMES, ICON_NAMES, LEGACY_ICON_NAMES } from "./names";
import { SUBSET_FILE, WOFF2_REQUEST, WOFF2_URL, buildSubsetCss, glyphCodepoints } from "./subset";

/**
 * Every `IconName` must exist in the GENERATED subset sheet — the file the apps actually bundle
 * (#1893: `icons.css` imports `phosphor-fill.subset.css`, not the full `@phosphor-icons/web`
 * sheet). The subset is generated from the INSTALLED fill sheet, resolved through the package's
 * own `exports` (`@phosphor-icons/web/fill`), and this file proves the checked-in subset is
 * exactly what the generator produces today — regenerate-and-diff — so it can be neither stale
 * nor hand-edited. Parsed as strings with static patterns (no `RegExp` built from a variable).
 */
const require = createRequire(import.meta.url);
const FILL_CSS_PATH = require.resolve("@phosphor-icons/web/fill");
const FILL_CSS = readFileSync(FILL_CSS_PATH, "utf8");
const PKG_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SUBSET_PATH = join(PKG_ROOT, SUBSET_FILE);
const SUBSET_CSS = readFileSync(SUBSET_PATH, "utf8");

/** name → the `content` codepoint of each `.ph-fill.ph-<name>:before` rule. */
const RULES = glyphCodepoints(FILL_CSS);
const SUBSET_RULES = glyphCodepoints(SUBSET_CSS);

describe("the fill sheet parse is real (so a pass below means something)", () => {
  it("finds the whole sheet — Phosphor ships ~1,500 fill glyphs", () => {
    expect(RULES.size).toBeGreaterThan(1500);
  });

  it("finds a known glyph and rejects a misspelt one", () => {
    expect(RULES.get("plus")).toMatch(/^\\[0-9a-f]{4}$/);
    expect(RULES.has("plsu")).toBe(false);
  });
});

describe("IconName ⊂ the generated subset sheet (what the apps bundle)", () => {
  it("every canonical and legacy name has a `.ph-fill.ph-<name>:before` rule with a codepoint", () => {
    const missing = ALL_ICON_NAMES.filter((n) => !SUBSET_RULES.has(n));
    expect(
      missing,
      `not in ${SUBSET_PATH} — run: pnpm --filter @badabhai/icons generate:subset`,
    ).toEqual([]);
    for (const n of ALL_ICON_NAMES) expect(SUBSET_RULES.get(n), n).toMatch(/^\\[0-9a-f]{4}$/);
  });

  it("carries ONLY the union — no glyph nothing can name", () => {
    expect([...SUBSET_RULES.keys()].sort()).toEqual([...new Set(ALL_ICON_NAMES)].sort());
  });

  it("each codepoint is the installed sheet's own (copied, never re-typed)", () => {
    for (const [n, cp] of SUBSET_RULES) expect(cp, n).toBe(RULES.get(n));
  });

  it("names are sorted and unique (reviewable diffs, no accidental duplicates)", () => {
    for (const list of [ICON_NAMES, LEGACY_ICON_NAMES] as const) {
      expect([...list]).toEqual([...new Set(list)].sort());
    }
  });

  it("a retired (legacy) name is never also canonical", () => {
    const canonical = new Set<string>(ICON_NAMES);
    expect(LEGACY_ICON_NAMES.filter((n) => canonical.has(n))).toEqual([]);
  });
});

describe("the dependency is pinned and self-hostable", () => {
  const manifest = JSON.parse(readFileSync(join(PKG_ROOT, "package.json"), "utf8")) as {
    dependencies: Record<string, string>;
  };
  const installed = JSON.parse(
    readFileSync(join(dirname(FILL_CSS_PATH), "..", "..", "package.json"), "utf8"),
  ) as { name: string; version: string };

  it("pins an EXACT version (no range) and that version is what is installed", () => {
    const spec = manifest.dependencies["@phosphor-icons/web"];
    expect(spec).toMatch(/^\d+\.\d+\.\d+$/);
    expect(installed.name).toBe("@phosphor-icons/web");
    expect(installed.version).toBe(spec);
  });

  it("the sheet's @font-face points at a RELATIVE woff2 that ships beside it", () => {
    expect(FILL_CSS).toContain('url("./Phosphor-Fill.woff2") format("woff2")');
    expect(existsSync(join(dirname(FILL_CSS_PATH), "Phosphor-Fill.woff2"))).toBe(true);
  });

  it("the sheet references no absolute or third-party URL (nothing leaves the app's origin)", () => {
    for (const m of FILL_CSS.matchAll(/url\(\s*["']?([^"')]+)/g)) {
      expect(m[1], "every font url must be relative").toMatch(/^\.\//);
    }
    expect(FILL_CSS).not.toMatch(/https?:|\/\/[a-z]/i);
  });
});

describe("the subset sheet is generated, and up to date", () => {
  it("is byte-identical to what scripts/generate-subset.mts produces from the installed sheet", () => {
    // A stale file (a glyph added to names.ts, or the pin bumped, without regenerating) or a
    // hand edit fails here. Fix: pnpm --filter @badabhai/icons generate:subset
    expect(SUBSET_CSS).toBe(buildSubsetCss(FILL_CSS, ALL_ICON_NAMES));
  });

  it("says it is generated, and how to regenerate it", () => {
    expect(
      SUBSET_CSS.startsWith("/* GENERATED by packages/icons/scripts/generate-subset.mts"),
    ).toBe(true);
    expect(SUBSET_CSS).toContain("pnpm --filter @badabhai/icons generate:subset");
  });

  it("declares a woff2-ONLY @font-face, through the installed package (self-hosted)", () => {
    const urls = [...SUBSET_CSS.matchAll(/url\(\s*"([^"]+)"\s*\)\s*format\("([^"]+)"\)/g)];
    expect(urls.map((m) => [m[1], m[2]])).toEqual([[WOFF2_URL, "woff2"]]);
    expect(WOFF2_URL).toBe(`~${WOFF2_REQUEST}`);
    expect(SUBSET_CSS).not.toMatch(/\.(woff|ttf|svg)\b(?!2)/);
    expect(SUBSET_CSS).not.toMatch(/https?:/);
    // The request resolves (via the package's "./*" export) to the woff2 the full sheet ships.
    expect(require.resolve(WOFF2_REQUEST)).toBe(
      join(dirname(FILL_CSS_PATH), "Phosphor-Fill.woff2"),
    );
  });

  it("keeps the face's other descriptors and the .ph-fill base rule exactly as Phosphor ships them", () => {
    expect(SUBSET_CSS).toContain('font-family: "Phosphor-Fill";');
    expect(SUBSET_CSS).toContain("font-display: block;");
    const base = (css: string) =>
      css.slice(css.search(/^\.ph-fill \{/m), css.indexOf("}", css.search(/^\.ph-fill \{/m)) + 1);
    expect(base(SUBSET_CSS)).toBe(base(FILL_CSS));
  });

  it("the generator refuses a name the installed sheet lacks, rather than emit a partial sheet", () => {
    expect(() => buildSubsetCss(FILL_CSS, ["plus", "plsu"])).toThrow(/plsu/);
  });

  it("is a small fraction of the full sheet", () => {
    expect(SUBSET_RULES.size).toBe(new Set(ALL_ICON_NAMES).size);
    expect(SUBSET_CSS.length * 5).toBeLessThan(FILL_CSS.length);
  });
});
