/**
 * Build the SUBSET Phosphor FILL stylesheet (#1893): only the glyphs in the `IconName` union,
 * and a woff2-only `@font-face`.
 *
 * The full `@phosphor-icons/web` fill sheet carries ~1,530 glyph rules and lists four font
 * formats, so every app build emitted all four files (svg ≈2.77 MB, ttf and woff ≈449 KB each)
 * although a browser only ever fetches the woff2, and every page paid ~12 KB gzipped of
 * render-blocking CSS for glyphs nothing draws.
 *
 * PURE: text in, text out. `scripts/generate-subset.mts` writes the result to
 * `phosphor-fill.subset.css`, and `names.test.ts` regenerates it in memory and fails when the
 * checked-in file differs — so the file is never hand-edited and never stale.
 *
 * The rules are COPIED from the installed sheet, never re-typed: the base `.ph-fill` rule
 * verbatim, and each glyph's `content` codepoint as Phosphor ships it. Parsed with static
 * patterns only (no `RegExp` built from a name).
 */

/** The generated sheet, at the package root (beside `icons.css`, which imports it). */
export const SUBSET_FILE = "phosphor-fill.subset.css";

/**
 * The woff2, as a MODULE request through `@phosphor-icons/web`'s `"./*"` export. The bundler
 * resolves it from this package's own dependency and emits it under `/_next/static/media`, so
 * the face is still self-hosted from each app's origin — and it is the ONLY format emitted.
 */
export const WOFF2_REQUEST = "@phosphor-icons/web/fill/Phosphor-Fill.woff2";

/**
 * How the sheet writes it: `~` marks a module request for the css-loader Next ships (a bare
 * `url(pkg/…)` is resolved as `./pkg/…`, relative to this file, and fails the build).
 */
export const WOFF2_URL = `~${WOFF2_REQUEST}`;

const HEADER = `/* GENERATED by packages/icons/scripts/generate-subset.mts — DO NOT EDIT BY HAND.
   Regenerate: pnpm --filter @badabhai/icons generate:subset
   Source: the installed @phosphor-icons/web fill sheet, filtered to the IconName union
   (src/names.ts), with a woff2-only @font-face. names.test.ts fails when this file is stale. */
`;

/** Each `.ph-fill.ph-<name>:before { content: "…"; }` rule in the sheet: name → codepoint. */
export function glyphCodepoints(fillCss: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const m of fillCss.matchAll(
    /\.ph-fill\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"([^"]+)";?\s*\}/g,
  )) {
    out.set(m[1]!, m[2]!);
  }
  return out;
}

function block(css: string, prelude: RegExp, what: string): string {
  const m = prelude.exec(css);
  if (!m) throw new Error(`subset: the fill sheet has no ${what} rule`);
  const end = css.indexOf("}", m.index);
  if (end < 0) throw new Error(`subset: the fill sheet's ${what} rule is unterminated`);
  return css.slice(m.index, end + 1);
}

/** The `@font-face` with its `src` cut to the woff2 alone; every other descriptor kept. */
function woff2FontFace(fillCss: string): string {
  const face = block(fillCss, /@font-face\s*\{/, "@font-face");
  const src = /\bsrc:[^;]*;/.exec(face);
  if (!src || !src[0].includes('format("woff2")')) {
    throw new Error("subset: the fill sheet's @font-face lists no woff2 source");
  }
  return face.replace(src[0], `src: url("${WOFF2_URL}") format("woff2");`);
}

/**
 * The subset sheet for `names` (sorted, de-duplicated). Throws — never emits a partial sheet —
 * when a name has no glyph in the installed version or the sheet's shape has changed.
 */
export function buildSubsetCss(fillCss: string, names: readonly string[]): string {
  const codepoints = glyphCodepoints(fillCss);
  const wanted = [...new Set(names)].sort();
  const missing = wanted.filter((n) => !codepoints.has(n));
  if (missing.length > 0) {
    throw new Error(`subset: not in the installed fill sheet: ${missing.join(", ")}`);
  }
  const base = block(fillCss, /^\.ph-fill\s*\{/m, ".ph-fill base");
  const glyphs = wanted.map(
    (n) => `.ph-fill.ph-${n}:before {\n  content: "${codepoints.get(n)}";\n}`,
  );
  return [HEADER, woff2FontFace(fillCss), "", base, "", ...glyphs, ""].join("\n");
}
