import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { JobCardPreview } from "./job-card-preview";
import { JOB_CARD_CLAMPS, type CardFields } from "../lib/job-card-view";

/**
 * PREVIEW == WORKER CARD, pinned against a checked-in fixture of inputs → the exact text the
 * worker's `Design1JobCard` draws, in order (packages/types/fixtures/job-card-contract.json — its
 * expected strings were written from the Dart formatters, not generated by this client, so a mock
 * that renders anything cannot pass). The same file is readable by a Dart widget test, so both
 * sides can be held to ONE contract.
 *
 * For each case: the fixture input → CardFields → the REAL preview markup → its `data-slot`
 * elements in DOM order (slot, chip kind, text) must EQUAL the expected list, and every clamped
 * slot's `data-clamp` must equal the fixture's clamp (= the phone's `maxLines`).
 */

const here = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = join(
  here,
  "..",
  "..",
  "..",
  "..",
  "packages",
  "types",
  "fixtures",
  "job-card-contract.json",
);

interface Slot {
  slot: string;
  text: string;
  kind?: string;
}
interface Fixture {
  version: number;
  clamps: Record<string, number>;
  cases: Array<{ name: string; input: Record<string, unknown>; expected: Slot[] }>;
}
const FIXTURE = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;

/** The GET /feed wire keys (as the worker app reads them) → the preview's CardFields. */
function cardFromFeedInput(input: Record<string, unknown>): CardFields {
  const str = (k: string) => (typeof input[k] === "string" ? (input[k] as string) : null);
  const num = (k: string) => (typeof input[k] === "number" ? (input[k] as number) : null);
  const list = (k: string) => (Array.isArray(input[k]) ? (input[k] as string[]) : []);
  return {
    role_title: str("title"),
    role_kind: null,
    city: str("city"),
    area: str("area"),
    pay_min: num("pay_min"),
    pay_max: num("pay_max"),
    pay_type: str("pay_type"),
    min_experience_years: num("min_experience_years"),
    max_experience_years: num("max_experience_years"),
    shift: str("shift"),
    needed_by: str("needed_by"),
    requirements: list("requirements"),
    benefits: list("benefits"),
  };
}

const ENTITIES: Record<string, string> = {
  "&amp;": "&",
  "&lt;": "<",
  "&gt;": ">",
  "&quot;": '"',
  "&#x27;": "'",
};
const decode = (s: string) => s.replace(/&(?:amp|lt|gt|quot|#x27);/g, (e) => ENTITIES[e] ?? e);
const VOID_TAGS = new Set(["br", "img", "input", "hr", "meta", "link"]);
const TOKEN = /<(\/?)([a-zA-Z][a-zA-Z0-9]*)((?:\s+[^>]*?)?)\s*(\/?)>|([^<]+)/g;
const ATTR_SLOT = /\sdata-slot="([^"]*)"/;
const ATTR_KIND = /\sdata-kind="([^"]*)"/;
const ATTR_CLAMP = /\sdata-clamp="([^"]*)"/;

/** The `data-slot` leaves of rendered markup, in document order, with their text and clamp. */
function slotsOf(markup: string): Array<Slot & { clamp: number | null }> {
  const out: Array<Slot & { clamp: number | null }> = [];
  const stack: Array<{ slot: (Slot & { clamp: number | null }) | null; text: string[] }> = [];
  for (const m of markup.matchAll(TOKEN)) {
    if (m[5] !== undefined) {
      for (const frame of stack) if (frame.slot) frame.text.push(decode(m[5]));
      continue;
    }
    const [, closing, tag, attrs = "", selfClosing] = m;
    if (closing) {
      const frame = stack.pop();
      if (frame?.slot) out.push({ ...frame.slot, text: frame.text.join("") });
      continue;
    }
    if (VOID_TAGS.has(tag!.toLowerCase()) || selfClosing) continue;
    const slot = ATTR_SLOT.exec(attrs)?.[1];
    const kind = ATTR_KIND.exec(attrs)?.[1];
    const clamp = ATTR_CLAMP.exec(attrs)?.[1];
    stack.push({
      slot:
        slot === undefined
          ? null
          : { slot, text: "", ...(kind ? { kind } : {}), clamp: clamp ? Number(clamp) : null },
      text: [],
    });
  }
  return out;
}

describe("the worker-card contract fixture", () => {
  it("is the version this suite reads, with the phone's clamps", () => {
    expect(FIXTURE.version).toBe(1);
    expect(FIXTURE.cases.length).toBeGreaterThanOrEqual(15);
    expect(JOB_CARD_CLAMPS).toEqual(FIXTURE.clamps);
  });

  it("the slot reader sees what it should (a reader that saw nothing would pass everything)", () => {
    const slots = slotsOf(
      renderToStaticMarkup(<JobCardPreview fields={cardFromFeedInput(FIXTURE.cases[0]!.input)} />),
    );
    expect(slots.length).toBe(FIXTURE.cases[0]!.expected.length);
    expect(slots[0]).toMatchObject({ slot: "title", clamp: 2 });
  });

  it.each(FIXTURE.cases.map((c) => [c.name, c] as const))("%s", (_name, c) => {
    const markup = renderToStaticMarkup(<JobCardPreview fields={cardFromFeedInput(c.input)} />);
    const slots = slotsOf(markup);
    // Order, kinds and text: exactly the worker card's.
    expect(slots.map(({ clamp: _c, ...s }) => s)).toEqual(c.expected);
    // Every clamped slot carries the phone's maxLines.
    for (const s of slots) {
      const expectedClamp = FIXTURE.clamps[s.slot];
      expect(s.clamp, `${s.slot} clamp`).toBe(expectedClamp ?? null);
    }
  });
});
