ALTER TABLE "worker_consents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profiling_family" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profiling_family_binding" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question_pack_item" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question_pack_option" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question_pack" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "voice_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profiling_voice_answer" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "worker_attributes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "generated_resumes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profile_questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "worker_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "applications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "job_postings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "credit_ledger" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "payer_capacity" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "payer_credits" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "posting_boosts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "posting_plans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "pricing_catalog" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "resume_disclosures" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "unlock_routing" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "unlocks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ai_jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;