-- ===========================================================================
-- S3-C / D-6 — `unresolved_phrase.job_domain_id`
--
-- GENERATED BY `db:generate`, THEN HAND-EDITED. The statement SET and every identifier
-- below are drizzle's own output, so a re-run diffs clean against `meta/0078_snapshot.json`.
-- What is hand-added: `NULLS NOT DISTINCT` on the unique index (see below), this header,
-- and the rollback footer. Re-running the generator WILL drop the clause again — that is
-- the whole reason `unresolved-phrase-job-domain.test.ts` pins it.
--
-- WHAT THIS UNBLOCKS, PRECISELY. Path A (canonical retrieval) is scoped by `job_domain_id`;
-- Path B (legacy) by the `domain_id` slug. A canonical-scoped canonicalization that MISSES
-- has, today, nowhere to record WHICH domain it missed in — `unresolved_phrase` models only
-- the legacy slug. Flipping the read switch before this column exists would make Path A's
-- failures invisible in the one table built to catch failures, which is why
-- `phase-9-s3-deployment-plan.md` promotes it from a follow-up to a hard S3-C prerequisite.
--
-- THE COLUMN IS THE EASY HALF. The load-bearing change is the UNIQUE INDEX.
-- `unresolved_phrase_scope_uq` was (scope, phrase, domain_id, lang) and it is what makes the
-- writer's atomic count-increment upsert work. Two canonical misses of the SAME phrase in
-- DIFFERENT job domains both carry `domain_id IS NULL`, so under the OLD key they collide
-- and merge into one row with a summed `count` — silently destroying the very distinction
-- this column is being added to record, in the direction that makes Path A look healthier
-- than it is. The key must include the new column or the column is decorative.
--
-- WHY RE-CREATING THAT INDEX IS SAFE HERE, rather than merely believed to be:
--   * every existing row gets `job_domain_id = NULL` (added with no DEFAULT), and the index
--     is NULLS NOT DISTINCT, so NULL = NULL for uniqueness. Appending an all-NULL column to
--     the key cannot split or merge any existing row: the equivalence classes over shipped
--     data are byte-identical to before.
--   * DROP + CREATE (not CONCURRENTLY) holds a lock for its duration. `unresolved_phrase`
--     held 9 rows in production when this was authored — measured, not assumed — so the
--     window is sub-millisecond. CONCURRENTLY is not available anyway: drizzle runs each
--     migration inside a transaction, and CREATE INDEX CONCURRENTLY cannot run in one.
--
-- NULLS NOT DISTINCT IS HAND-APPENDED, for the fourth time in this schema and for the same
-- reason 0037 / 0067 / 0072 / 0076 all did it: this drizzle version models the clause on a
-- table CONSTRAINT but never on an INDEX. Verified again here — the generator's own output
-- for this migration omitted it. Dropping it would be an ACTIVE regression, not a missing
-- nicety: the occupation scope has written `domain_id = NULL` since 0070 and depends on
-- NULLs deduping onto a single row.
--
-- ADDITIVE, REVERSIBLE, NO BACKFILL, NO ROW REWRITE. A nullable column with no DEFAULT is
-- catalogue-only on PG11+.
--
-- APPLY THIS BEFORE DEPLOYING THE CODE THAT CARRIES IT. `SkillsRepository.recordUnresolved`
-- names `job_domain_id` in the INSERT list and in the ON CONFLICT target UNCONDITIONALLY — a
-- legacy or occupation miss binds NULL for it, but the column must exist. Against a database
-- without this migration EVERY unresolved write fails (42703, or 42P10 on the conflict target,
-- which has to name the widened index's exact five columns), including the occupation path that
-- runs on every below-floor trade phrase in a live interview. That path is fail-soft — the
-- interview is unaffected and the loss is growth signal — but it is still loss.
-- ===========================================================================

DROP INDEX "unresolved_phrase_scope_uq";--> statement-breakpoint
ALTER TABLE "unresolved_phrase" ADD COLUMN "job_domain_id" text;--> statement-breakpoint

-- FK to the canonical domain table, mirroring `job_postings.job_domain_id` (0076). A miss
-- can only name a domain that exists. `job_domain` rows are status-managed and never deleted
-- (ADR-0030 SG-5), so NO ACTION can never fire in practice — and is still the right choice
-- if it ever did, because a cascade would silently discard growth signal. The validating
-- scan is over rows that are all NULL, i.e. trivially satisfied.
ALTER TABLE "unresolved_phrase" ADD CONSTRAINT "unresolved_phrase_job_domain_id_job_domain_job_domain_id_fk" FOREIGN KEY ("job_domain_id") REFERENCES "public"."job_domain"("job_domain_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint

-- The canonical-scope ops read ("show me unresolved phrases for this trade") and the FK's
-- own lookup. Postgres does not auto-index a referencing column.
CREATE INDEX "unresolved_phrase_job_domain_id_idx" ON "unresolved_phrase" USING btree ("job_domain_id");--> statement-breakpoint

-- HAND-EDITED: `NULLS NOT DISTINCT` appended (PG15+) — see the header. `scope` still LEADS
-- (the ops queue reads one scope at a time); `job_domain_id` sits beside `domain_id` because
-- the two are mutually exclusive per the CHECK below, so exactly one of them carries
-- information in any given row.
CREATE UNIQUE INDEX "unresolved_phrase_scope_uq" ON "unresolved_phrase" USING btree ("scope","phrase","domain_id","job_domain_id","lang") NULLS NOT DISTINCT;--> statement-breakpoint

-- A row is scoped by AT MOST ONE vocabulary. Three legal shapes, and this forbids the fourth:
--   legacy skill miss     domain_id set,  job_domain_id null
--   canonical skill miss  domain_id null, job_domain_id set
--   occupation miss       both null                            (legal since 0070)
--   BOTH set              meaningless — which vocabulary did it fail in?
-- A CHECK rather than an application rule because unrepresentable beats merely rejected:
-- the growth runner and every future writer inherit it without reading the DTO. Every
-- existing row satisfies it (job_domain_id is NULL for all of them).
ALTER TABLE "unresolved_phrase" ADD CONSTRAINT "unresolved_phrase_one_domain_chk" CHECK ("unresolved_phrase"."domain_id" IS NULL OR "unresolved_phrase"."job_domain_id" IS NULL);

-- ===========================================================================
-- ROLLBACK. Safe ONLY while no row carries a non-null `job_domain_id`; once canonical
-- misses exist, dropping the column discards growth signal, so re-derive it from
-- `skill.phrase_unresolved_v2` on the event spine first.
--
--   DROP INDEX "unresolved_phrase_job_domain_id_idx";
--   DROP INDEX "unresolved_phrase_scope_uq";
--   CREATE UNIQUE INDEX "unresolved_phrase_scope_uq" ON "unresolved_phrase"
--     USING btree ("scope","phrase","domain_id","lang") NULLS NOT DISTINCT;
--   ALTER TABLE "unresolved_phrase" DROP CONSTRAINT "unresolved_phrase_one_domain_chk";
--   ALTER TABLE "unresolved_phrase" DROP CONSTRAINT
--     "unresolved_phrase_job_domain_id_job_domain_job_domain_id_fk";
--   ALTER TABLE "unresolved_phrase" DROP COLUMN "job_domain_id";
-- ===========================================================================
