import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:badabhai_worker_app/core/api/api_models.dart';
import 'package:badabhai_worker_app/core/util/pay_format.dart';
import 'package:badabhai_worker_app/features/swipe/presentation/swipe_jobs_screen.dart';
import 'package:badabhai_worker_app/features/swipe/presentation/widgets/design1_job_card.dart';

/// #1888 — pin [Design1JobCard] to the SAME shared contract the payer-web preview reads:
/// `packages/types/fixtures/job-card-contract.json` (posting inputs → the exact text the worker's
/// swipe card draws, in order). The fixture's strings were written from the Dart formatters
/// (`pay_format.dart` / `job_display.dart`), not generated by either client, so a card that drifts
/// fails here — and the payer is never shown a card the worker does not get.
///
/// The card is fed through the SCREEN's own mapper (`feedItemCardData`) and the deck's own
/// `formatPayBandFull`, so the test exercises the real wiring, not a parallel copy.
void main() {
  final File fixtureFile =
      File('../../packages/types/fixtures/job-card-contract.json');
  final Map<String, dynamic> fixture =
      jsonDecode(fixtureFile.readAsStringSync()) as Map<String, dynamic>;
  final List<Map<String, dynamic>> cases =
      (fixture['cases'] as List<dynamic>).cast<Map<String, dynamic>>();

  test('the fixture is the version this suite reads, with cases', () {
    expect(fixture['version'], 1);
    expect(cases.length, greaterThanOrEqualTo(15));
  });

  for (int i = 0; i < cases.length; i++) {
    final Map<String, dynamic> c = cases[i];
    final String name = c['name'] as String;
    final Map<String, dynamic> input =
        (c['input'] as Map<String, dynamic>);
    final List<Map<String, dynamic>> expected =
        (c['expected'] as List<dynamic>).cast<Map<String, dynamic>>();

    testWidgets('card contract · $name', (WidgetTester tester) async {
      // A job id is required by FeedItem.fromJson but not part of the card contract.
      final FeedItem item = FeedItem.fromJson(<String, dynamic>{
        ...input,
        'job_id': 'fixture-$i',
      });
      final String? payFull = formatPayBandFull(item.payMin, item.payMax);

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SingleChildScrollView(
              child: Design1JobCard(
                data: feedItemCardData(item),
                payFull: payFull,
                // The deck passes exactly this (its behind card + dock own the rest).
                showDock: false,
                showTeaser: false,
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // Every expected slot is drawn…
      for (final Map<String, dynamic> slot in expected) {
        final String text = slot['text'] as String;
        expect(
          find.text(text),
          findsWidgets,
          reason: 'missing ${slot['slot']}="$text"',
        );
      }

      // …and the non-empty slots appear top-to-bottom in the fixture's order.
      double? lastTop;
      for (final Map<String, dynamic> slot in expected) {
        final String text = slot['text'] as String;
        if (text.isEmpty) continue; // an empty Text has no meaningful position
        final double top = tester.getTopLeft(find.text(text).first).dy;
        if (lastTop != null) {
          expect(
            top,
            greaterThanOrEqualTo(lastTop - 0.5),
            reason: 'order: "$text" (${slot['slot']}) sits above the previous slot',
          );
        }
        lastTop = top;
      }
    });
  }
}
